// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppReady() {
  return window['go']['main']['App']['AppReady']();
}

export function AutoDetectEnhanceEngine() {
  return window['go']['main']['App']['AutoDetectEnhanceEngine']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearFinishedJobs() {
  return window['go']['main']['App']['ClearFinishedJobs']();
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function EnqueueJob(arg1) {
  return window['go']['main']['App']['EnqueueJob'](arg1);
}

export function ExportPresets(arg1, arg2) {
  return window['go']['main']['App']['ExportPresets'](arg1, arg2);
}

export function FolderName(arg1) {
  return window['go']['main']['App']['FolderName'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetClipboardText() {
  return window['go']['main']['App']['GetClipboardText']();
}

export function GetGPUInfo() {
  return window['go']['main']['App']['GetGPUInfo']();
}

export function GetQueue() {
  return window['go']['main']['App']['GetQueue']();
}

export function ImportPresets() {
  return window['go']['main']['App']['ImportPresets']();
}

export function InspectDirectory(arg1) {
  return window['go']['main']['App']['InspectDirectory'](arg1);
}

export function IsDirectory(arg1) {
  return window['go']['main']['App']['IsDirectory'](arg1);
}

export function IsWindowMaximised() {
  return window['go']['main']['App']['IsWindowMaximised']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function MoveQueueJob(arg1, arg2) {
  return window['go']['main']['App']['MoveQueueJob'](arg1, arg2);
}

export function OpenFileExplorer(arg1) {
  return window['go']['main']['App']['OpenFileExplorer'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PauseProcessing() {
  return window['go']['main']['App']['PauseProcessing']();
}

export function RemoveQueueJob(arg1) {
  return window['go']['main']['App']['RemoveQueueJob'](arg1);
}

export function ResumeProcessing() {
  return window['go']['main']['App']['ResumeProcessing']();
}

export function RetryQueueJob(arg1) {
  return window['go']['main']['App']['RetryQueueJob'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectInputFile() {
  return window['go']['main']['App']['SelectInputFile']();
}

export function SelectWatermarkFile() {
  return window['go']['main']['App']['SelectWatermarkFile']();
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function StartQueue() {
  return window['go']['main']['App']['StartQueue']();
}

export function StopProcessing() {
  return window['go']['main']['App']['StopProcessing']();
}

export function ToggleMaximiseWindow() {
  return window['go']['main']['App']['ToggleMaximiseWindow']();
}
