// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppReady():Promise<void>;

export function CloseWindow():Promise<void>;

export function ExportPresets(arg1:string,arg2:string):Promise<string>;

export function FolderName(arg1:string):Promise<string>;

export function GetClipboardText():Promise<string>;

export function ImportPresets():Promise<string>;

export function IsDirectory(arg1:string):Promise<boolean>;

export function MinimizeWindow():Promise<void>;

export function OpenFileExplorer(arg1:string):Promise<void>;

export function PauseProcessing():Promise<void>;

export function ResumeProcessing():Promise<void>;

export function SaveSettings(arg1:Record<string, any>):Promise<void>;

export function SelectFolder():Promise<string>;

export function SelectWatermarkFile():Promise<string>;

export function Start(arg1:Record<string, any>):Promise<void>;

export function StopProcessing():Promise<void>;
