// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppReady() {
  return window['go']['main']['App']['AppReady']();
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function ExportPresets(arg1, arg2) {
  return window['go']['main']['App']['ExportPresets'](arg1, arg2);
}

export function FolderName(arg1) {
  return window['go']['main']['App']['FolderName'](arg1);
}

export function GetClipboardText() {
  return window['go']['main']['App']['GetClipboardText']();
}

export function ImportPresets() {
  return window['go']['main']['App']['ImportPresets']();
}

export function IsDirectory(arg1) {
  return window['go']['main']['App']['IsDirectory'](arg1);
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenFileExplorer(arg1) {
  return window['go']['main']['App']['OpenFileExplorer'](arg1);
}

export function PauseProcessing() {
  return window['go']['main']['App']['PauseProcessing']();
}

export function ResumeProcessing() {
  return window['go']['main']['App']['ResumeProcessing']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectWatermarkFile() {
  return window['go']['main']['App']['SelectWatermarkFile']();
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function StopProcessing() {
  return window['go']['main']['App']['StopProcessing']();
}
